- pizza-time/package.json
- pizza-time/src/App.js
- pizza-time/src/events/events.js
- pizza-time/src/favorites/favorites.js
- pizza-time/src/footer/footer.js
- pizza-time/src/friends-lists/friends-list.js
- pizza-time/src/index.js
- pizza-time/src/landing-page/landing.js
- pizza-time/src/login/login.js
- pizza-time/src/nav/nav.js
- pizza-time/src/user-dashboard/user-dashboard.js
- pizza-time/yarn.lock
so we can nav to the component we are working on easily
> added basic routes 

- pizza-time/public/index.html
- pizza-time/public/reset.css
- pizza-time/src/App.js
- pizza-time/src/components/landing-page/landing.js
- pizza-time/src/styles/landingStyles.js
- Created landing page component
- Styled landing page component
> Landing - AY

- pizza-time/src/App.js
- pizza-time/src/components/events/events.js
- pizza-time/src/components/events/search/places-search.js
- pizza-time/src/components/favorites/favorites.js
- pizza-time/src/components/friends-lists/friends-list.js
- pizza-time/src/components/user-dashboard/user-dashboard.js
- Placed nav in footer in the correct components
> Refactoring - AY

- pizza-time/src/App.js
- pizza-time/src/admin/UsersList.js
> Users list ab

- pizza-time/package.json
- pizza-time/src/components/card/card.js
- pizza-time/src/components/home-header/home-header.js
- pizza-time/src/containers/user-dashboard/user-dashboard.js
- pizza-time/src/styles/cardStyles.js
- pizza-time/src/styles/navStyles.js
- pizza-time/src/styles/userhomeStyles.js
- pizza-time/yarn.lock
- Completed Header for userhome
- Completed userhome component
- Working on individual (card) component
> Userhome - AY

- pizza-time/src/containers/register/Register.js
- pizza-time/src/firebase/authProviders.js
Adds a google provider and allows google sign-in on the front end.
> Google sign in ns

- pizza-time/src/containers/login/login.js
Adds google sign in button and logic to register and signin components
> Adds button to sign in with google in Sign In Component

- pizza-time/src/components/home-header/home-header.js
> added link to create event flow

- pizza-time/src/styles/cardStyles.js
- pizza-time/src/styles/eventStyles.js
- pizza-time/src/styles/landingStyles.js
- pizza-time/src/styles/navStyles.js
- pizza-time/src/styles/registerLoginStyles.js
- pizza-time/src/styles/userhomeStyles.js
- pizza-time/src/styles/variables.js
- Refactored all theme styles into its own file that needs to be imported into every styledcomponents file for use.
> refactored theme styles

- pizza-time/package.json
- pizza-time/src/components/private-route/PrivateRoute.js
- pizza-time/src/components/private/Private.js
- pizza-time/src/containers/login/login.js
- pizza-time/src/containers/register/Register.js
- pizza-time/src/containers/register/registerUtils.js
- pizza-time/src/firebase/authorizedRequest.js
- pizza-time/yarn.lock
-Makes a function that allows you to make a  request with  token from firebase automatically attached to it.  this could also be done with axios.
-Adds login with google button.
-Updates the private component with demos on how to make all requests.
> Test claims ns

- pizza-time/src/components/events/SingleEvent/eventView.js
- pizza-time/src/components/events/SingleEvent/info.js
- pizza-time/src/data/data.js
> fix calendar date

- pizza-time/package.json
- pizza-time/src/components/events/SingleEvent/discussion.js
- pizza-time/src/components/events/SingleEvent/eventView.js
- pizza-time/src/components/events/SingleEvent/info.js
- pizza-time/src/components/events/SingleEvent/participants.js
- pizza-time/src/styles/eventStyles.js
- pizza-time/yarn.lock
add axios call to fetch single event
add google map
clean code
> Event api fe

- pizza-time/package.json
- pizza-time/src/App.js
- pizza-time/src/actions/index.js
- pizza-time/src/actions/userActions.js
- pizza-time/src/index.js
- pizza-time/src/reducers/index.js
- pizza-time/src/reducers/userReducer.js
- pizza-time/yarn.lock
this adds redux to the project.  It simply connects it to the app  and adds a basic file structure.
I also put a skeleton action and reducer  that I need to work with my components
> Add redux ns

- pizza-time/src/components/events/SingleEvent/discussion.js
- pizza-time/src/components/events/SingleEvent/eventView.js
fix error for reusable function, remove console logs
> Fix eventView function error

- pizza-time/package.json
- pizza-time/src/components/events/SingleEvent/discussion.js
- pizza-time/src/components/events/SingleEvent/eventView.js
- pizza-time/src/components/events/SingleEvent/info.js
- pizza-time/src/components/events/SingleEvent/participants.js
- pizza-time/src/styles/eventStyles.js
- add loading image while updating the event
- update the event using the events current state
- add update form w/ show display on click property
- pass down new methods - editing & saving w/ click handlers
- clean code, add basic css
> ADD UPDATE EVENT FUNCTIONALITY TO SINGLE EVENT

- pizza-time/src/components/events/SingleEvent/eventView.js
- pizza-time/src/components/events/SingleEvent/participants.js
- pizza-time/src/styles/eventStyles.js
refactor current code to add nviting Users functionality
when clicking to add, show the friends who are not invited
remove console logs, unused code
> Single event invite friends ab

- pizza-time/src/components/favorites-list/FavoritesList.js
- pizza-time/src/components/favorites/Favorites.js
Converts component into class component
Makes Calls from places api to get list of places
Filter places based off of a drop down
Still needs styling but functionality is there.
Still needs search for new favorite functionality
> Favorites list ns

- pizza-time/package.json
- pizza-time/src/components/friend-card/FriendCard.js
- pizza-time/src/components/friends-list/FriendsList.js
- pizza-time/src/styles/profileStyles.js
- pizza-time/yarn.lock
Adds Buttons and styling to the friendslist components
> Friends list buttons

- pizza-time/src/App.js
- pizza-time/src/components/events/SingleEvent/discussion.js
- pizza-time/src/components/events/SingleEvent/editLocation.js
- pizza-time/src/components/events/SingleEvent/eventView.js
- pizza-time/src/components/events/SingleEvent/info.js
- pizza-time/src/components/events/SingleEvent/participants.js
- pizza-time/src/components/favorites-list/FavoritesList.js
- pizza-time/src/components/home-header/home-header.js
- pizza-time/src/containers/landing-page/landing.js
- pizza-time/src/styles/createNewEventStyles.js
add class to default avatar, remove unused code
hide buttons from non-organizer users for events name, save, delete &…
add state user to addComment function
clean up carousel by removing the events array from the carousel state
> Hide action button if not organizer ab

- pizza-time/src/App.js
- pizza-time/src/containers/login/login.js
- pizza-time/src/containers/register/Register.js
- pizza-time/src/containers/register/registerUtils.js
adds routing to login and register pages
> Login register flow ns

- pizza-time/src/components/favorites-list/FavoritesList.js
- pizza-time/src/components/favorites/Favorites.js
Adds keys to lists
removes the google API on favorites un mount
> Favorites google fix ns

- pizza-time/package.json
- pizza-time/src/App.css
- pizza-time/src/components/events/SingleEvent/discussion.js
- pizza-time/src/components/events/SingleEvent/eventView.js
- pizza-time/src/components/events/SingleEvent/info.js
- pizza-time/src/components/events/SingleEvent/locationMap.js
- pizza-time/src/components/events/SingleEvent/participants.js
- pizza-time/src/reducers/userReducer.js
- pizza-time/src/styles/eventStyles.js
- pizza-time/yarn.lock
show location's google map w/ marker
> Display location map ab

- pizza-time/src/App.css
- pizza-time/src/components/events/SingleEvent/discussion.js
- pizza-time/src/components/events/SingleEvent/editLocation.js
- pizza-time/src/components/events/SingleEvent/info.js
- pizza-time/src/styles/eventStyles.js
add organizer avatar, edit input error message
remove unused code, logs
> Organizer avatar ab

- pizza-time/package.json
- pizza-time/src/components/card/card.js
- pizza-time/src/components/events/SingleEvent/discussion.js
- pizza-time/src/components/events/SingleEvent/editLocation.js
- pizza-time/src/components/events/SingleEvent/info.js
- pizza-time/src/containers/login/login.js
- pizza-time/src/containers/user-dashboard/user-dashboard.js
- pizza-time/src/styles/registerLoginStyles.js
- pizza-time/yarn.lock
fix update comment
add login input errors
> Fixupdate comment ab

- pizza-time/src/components/card/card.js
- pizza-time/src/styles/cardStyles.js
> add style to userDashboard

- pizza-time/src/components/card/card.js
- pizza-time/src/containers/user-dashboard/user-dashboard.js
Reverts pizza-tim3/pizza-tim3-front#114
> Revert "fixed key itteration error and card claas error in user-dashboard.js …"

- pizza-time/src/containers/user-dashboard/user-dashboard.js
Reverts pizza-tim3/pizza-tim3-front#117
> Revert "added componentDidMount to user dashboard so it wouldn't look like th…"

- pizza-time/src/containers/user-dashboard/user-dashboard.js
Fix for missing place. Page was not loading.
> Fix for places not present
